### ISSUE TITLE
유저 엔티티 DTO 생성

### ISSUE THREAD

**Issue by no-cy** [f-lab-edu/market-nori#8]
## 🧑🏻‍💻 진행할 작업
- 유저 엔티티 DTO 생성
- DTO 객체 멤버 변수 Validation 설정

## 📝 TODO
- [x] id
- [x] password
- [x] name
- [x] phone
- [x] email
- [x] address

**Comment by f-lab-kane** [comment]
@no-cy 님, 해당 dto는 어디서 사용되는 dto인가요?

**Comment by no-cy** [comment]
@f-lab-kane 회원가입 시 Request Body 항목들을 받기 위한 DTO 입니다 !

**Comment by no-cy** [comment]
### 💡 멘토님 피드백 내용

- 일반적으로 한 개의 DTO를 생성하여 여러 API에서 같이 사용하지 않음
  - 그 이유는 각 API마다 요청, 응답 필드가 다르기 때문
- 회원가입에 사용될 DTO라고 하면, UserDto가 아닌 UserJoinDto로 작성하는 것이 적절함
  - **참고:** UserJoinRequest, UserJoinResponse 이름으로도 사용하기도 함
